/**
 * Extracts the ABIs the app and agent runtime need out of Hardhat artifacts into a single
 * typed module, so nothing outside the contracts pipeline has to import build output.
 *
 * Run automatically after `npm run compile`.
 */
import * as fs from "fs"
import * as path from "path"

const ROOT = path.resolve(__dirname, "..")
const OUT = path.join(ROOT, "src/lib/nodea/abi.ts")

const CONTRACTS = ["NodeaCredits", "NodeaSLA", "NodeaCompute", "NodeaPromptChannel"] as const

function findArtifact(name: string): string {
  const base = path.join(ROOT, "artifacts/contracts")
  const stack = [base]
  while (stack.length > 0) {
    const dir = stack.pop()!
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name)
      if (entry.isDirectory()) stack.push(full)
      else if (entry.name === `${name}.json`) return full
    }
  }
  throw new Error(`artifact not found for ${name} — run \`npm run compile\` first`)
}

const parts = CONTRACTS.map((name) => {
  const artifact = JSON.parse(fs.readFileSync(findArtifact(name), "utf8"))
  return `export const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const\n`
})

fs.mkdirSync(path.dirname(OUT), { recursive: true })
fs.writeFileSync(
  OUT,
  `// AUTO-GENERATED by scripts/export-abi.ts — do not edit by hand.\n` +
    `// Regenerate with \`npm run compile\`.\n\n` +
    parts.join("\n"),
)

console.log(`wrote ${path.relative(ROOT, OUT)} (${CONTRACTS.join(", ")})`)
